### ISSUE TITLE
Not able to open Crispy setup

### ISSUE THREAD

**Issue by nful2** [flathub/io.github.fabiangreffrath.Doom#10]
Wanted to change mouse acceleration, but couldn't because i was not able to open crispy setup. Cannot post logs as idk how to open it through terminal. I had to go to its config file to edit the acceleration. I have already used crispy setup on another distro, and it was MUCH easier to setup than editing config file.

**Comment by davidarnold** [comment]
Sorry about that!  This is an upstream bug, which I had a fix in place for but neglected to reapply in this latest release.

As a workaround until I release a new version with the fix reapplied, you can run:

```
flatpak run --command=crispy-doom-setup io.github.fabiangreffrath.Doom
```

**Comment by nful2** [comment]
Users need developers like you who give quick reply. Thanks!
