### ISSUE TITLE
Install desktop files for heretic and setup

### ISSUE THREAD

**Issue by Svadkos** [flathub/io.github.fabiangreffrath.Doom#2]
In the title.

**Comment by davidarnold** [comment]
@Svadkos Sorry, somehow I wasn't subscribed to notifications on the repo and missed this.

I'll give this another attempt the next release.  I tried to include this in the initial Flathub release, but Flatpak introduces some annoyances in trying to publish more than one .desktop file.

**Comment by davidarnold** [comment]
P.S. As a workaround you can launch these from the command line via:

- `flatpak run --command=crispy-doom-setup io.github.fabiangreffrath.Doom`
- `flatpak run --command=crispy-heretic io.github.fabiangreffrath.Doom`
- `flatpak run --command=crispy-heretic-setup io.github.fabiangreffrath.Doom`
